name: Update Docker Image

on:
  workflow_dispatch: {}

  push:
    branches: ["**"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: read
  packages: write

jobs:
  docker-image:
    uses: cusk-io/.github/.github/workflows/docker-build-push.yml@test-docker-build-push
    with:
      image_name: ghcr.io/cusk-io/presidio-analyzer
      timeout_minutes: 2
    secrets: inherit
